config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'connect', sign_out: 'disconnect', sign_up: 'enlist', edit: 'pilot' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  # Static Pages
  root 'static_pages#home'
  get '/credits', to: 'static_pages#credits'
  get '/nojs', to: 'static_pages#nojs'
  get '/support', to: 'static_pages#support'
  get '/donate', to: 'static_pages#donate'
  post '/support_ticket/create', to: 'static_pages#create_support_ticket', as: :create_support_ticket

  # Factions
  resources :factions, only: [:index]
  scope :factions do
    post 'choose', to: 'factions#choose_faction', as: :choose_faction
  end

  # Game
  get '/game', to: 'game#index'
  scope :game do
    post 'warp', to: 'game#warp'
    post 'jump', to: 'game#jump'
    get 'local_players', to: 'game#local_players'
    get 'ship_info', to: 'game#ship_info'
    get 'player_info', to: 'game#player_info'
    get 'chat', to: 'game#chat'
    get 'system_card', to: 'game#system_card'
    get 'locations_card', to: 'game#locations_card'
  end

  # User
  scope :user do
    get 'info/:id', to: 'users#info'
    post 'update_bio', to: 'users#update_bio'
    post 'place_bounty', to: 'users#place_bounty'
  end

  # Mails
  resources :game_mails, only: [:index, :new, :create, :show], path: 'mails'

  # Station
  scope :stations do
    post 'dock', to: 'stations#dock'
    post 'undock', to: 'stations#undock'
    post 'buy', to: 'stations#buy'
    post 'store', to: 'stations#store'
    post 'load', to: 'stations#load'
    post 'dice_roll', to: 'stations#dice_roll'
  end
  get '/station', to: 'stations#index'

  # Map
  get '/map', to: 'static_pages#map'

  # Assets
  get '/assets', to: 'game#assets'

  # Ships
  scope :ship do
    post 'activate', to: 'ships#activate'
    post 'target', to: 'ships#target'
    post 'untarget', to: 'ships#untarget'
    get 'cargohold', to: 'ships#cargohold'
    post 'eject_cargo', to: 'ships#eject_cargo'
    get 'info', to: 'ships#info'
    post 'insure', to: 'ships#insure'
    post 'custom_name', to: 'ships#custom_name'
    get 'upgrade_modal', to: 'ships#upgrade_modal'
    post 'upgrade', to: 'ships#upgrade'
  end

  # Asteroids
  scope :asteroid do
    post 'mine', to: 'asteroids#mine'
    post 'stop_mine', to: 'asteroids#stop_mine'
  end

  # NPCs
  scope :npc do
    post 'target', to: 'npcs#target'
    post 'untarget', to: 'npcs#untarget'
  end

  # Structures
  scope :structure do
    post 'open_container', to: 'structures#open_container'
    post 'pickup_cargo', to: 'structures#pickup_cargo'
    post 'attack', to: 'structures#attack'
    post 'abandoned_ship', to: 'structures#abandoned_ship'
    get 'monument_info', to: 'structures#monument_info'
  end

  # Friends
  get 'friends', to: 'friends#index'
  scope :friends do
    post 'add_friend', to: 'friends#add_friend'
    post 'accept_request', to: 'friends#accept_request'
    post 'remove_friend', to: 'friends#remove_friend'
    post 'search', to: 'friends#search'
  end

  # Chat
  scope :chat do
    post 'join', to: 'chat_rooms#join'
    post 'create', to: 'chat_rooms#create'
    post 'leave', to: 'chat_rooms#leave'
    post 'start_conversation', to: 'chat_rooms#start_conversation'
    post 'search', to: 'chat_rooms#search'
  end

  # Fleets
  scope :fleet do
    post 'invite', to: 'fleets#invite'
    post 'accept_invite', to: 'fleets#accept_invite'
    post 'remove', to: 'fleets#remove'
  end

  # Equipment
  scope :equipment do
    post 'update', to: 'equipment#update'
    post 'switch', to: 'equipment#switch'
    get 'info', to: 'equipment#info'
  end

  # Market
  scope :market do
    get 'list', to: 'market#list'
    get 'search', to: 'market#search'
    post 'buy', to: 'market#buy'
    post 'appraisal', to: 'market#appraisal'
    post 'sell', to: 'market#sell'
    get 'my_listings', to: 'market#my_listings'
    post 'delete_listing', to: 'market#delete_listing'
    post 'create_buy', to: 'market#create_buy'
    post 'fulfill_buy', to: 'market#fulfill_buy'
  end

  # Systems
  scope :system do
    get 'info', to: 'systems#info'
    post 'route', to: 'systems#route'
    post 'clear_route', to: 'systems#clear_route'
    post 'scan', to: 'systems#scan'
    post 'directional_scan', to: 'systems#directional_scan'
    post 'jump_drive', to: 'systems#jump_drive'
  end

  # Missions
  scope :mission do
    get 'info', to: 'missions#info'
    post 'accept', to: 'missions#accept'
    post 'finish', to: 'missions#finish'
    get 'popup', to: 'missions#popup'
    post 'abort', to: 'missions#abort'
  end

  # Blueprints
  scope :blueprint do
    post 'buy', to: 'blueprints#buy'
    get 'modal', to: 'blueprints#modal'
  end

  # Factory
  scope :factory do
    get 'modal', to: 'factories#modal'
    post 'craft', to: 'factories#craft'
    get 'dismantle_modal', to: 'factories#dismantle_modal'
    post 'dismantle', to: 'factories#dismantle'
  end

  # Corporation
  resources :corporations, only: [:index, :new, :create], path: 'corporation'
  scope :corporation do
    post 'update_motd', to: 'corporations#update_motd'
    post 'update_corporation', to: 'corporations#update_corporation'
    post 'kick_user', to: 'corporations#kick_user'
    get 'change_rank_modal', to: 'corporations#change_rank_modal'
    post 'change_rank', to: 'corporations#change_rank'
    post 'deposit_credits', to: 'corporations#deposit_credits'
    post 'withdraw_credits', to: 'corporations#withdraw_credits'
    get 'info', to: 'corporations#info'
    get 'apply_modal', to: 'corporations#apply_modal'
    post 'apply', to: 'corporations#apply'
    post 'accept_application', to: 'corporations#accept_application'
    post 'reject_application', to: 'corporations#reject_application'
    post 'disband', to: 'corporations#disband'
    post 'search', to: 'corporations#search'
    get 'sort_roster', to: 'corporations#sort_roster'
  end

  # Community
  scope :community do
    get '/', to: 'communities#index', as: :community
  end

  # Discourse
  get 'discourse/sso' => 'discourse_sso#sso'

  # Admin
  scope :admin do
    get '/', to: 'admin#index', as: :admin
    post 'search', to: 'admin#search'
    post 'teleport', to: 'admin#teleport'
    post 'set_credits', to: 'admin#set_credits'
    post 'ban', to: 'admin#ban'
    post 'unban', to: 'admin#unban'
    post 'server_message', to: 'admin#server_message'
    post 'mute', to: 'admin#mute'
    post 'unmute', to: 'admin#unmute'
    post 'delete_chat', to: 'admin#delete_chat'
  end

  # Polls
  scope :poll do
    post 'create', to: 'polls#create'
    post 'upvote', to: 'polls#upvote'
    post 'downvote', to: 'polls#downvote'
    post 'move_up', to: 'polls#move_up'
    post 'delete', to: 'polls#delete'
  end

  # ActionCable
  mount ActionCable.server => '/cable'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :credits, :nojs]
  skip_before_action :redirect_if_no_faction, only: [:home, :credits, :nojs, :create_support_ticket]

  def home
    redirect_to game_path if current_user
  end

  def credits
  end

  def nojs
  end

  def map
  end

  def create_support_ticket
    ApplicationMailer.with(category: params[:ticket][:category], subject: params[:ticket][:subject], description: params[:ticket][:description], name: current_user.full_name).support_ticket.deliver_now
    render json: { message: I18n.t('support.mail_sent_successfully') }, status: :ok
  end

  def donate
  end
end

app/views/static_pages/donate.html.erb
<div class="card black-card">
  <h5 class="card-header"><%= I18n.t('game.donate') %></h5>
  <div class="card-body">
    <div class="text-center">
      <p><%= I18n.t('game.donate_text').html_safe %></p>
      <p class="color-red"><%= I18n.t('game.donate_alert') %></p>
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
        <input type="hidden" name="cmd" value="_s-xclick" />
        <input type="hidden" name="hosted_button_id" value="PTXZHALEG5QAY" />
        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
        <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
      </form>
      
      <div class="mt-5">
        <h5><%= I18n.t('game.list_awesome_donators') %></h5>
          <% User.where(donator: true).each do |u| %>
              <%= u.full_name %><br>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="full-display container-fluid">
  <div class="body">
    <h1 class="text-center w-100 title"><strong>A NEW UNIVERSE AWAITS</strong></h1>
    <h3 class="text-center w-100 mb-3">WRITE YOUR OWN STORY</h3>
    <h1 class="text-center w-100">
      <a class="btn btn-primary btn-xl" href="#more_information"><%= I18n.t('game.more_information') %></a>
      <%= link_to I18n.t('game.play_for_free'), new_user_registration_path, class: 'btn btn-primary btn-xl' %>
      <div class="play-logo">
        <a href='https://play.google.com/store/apps/details?id=com.BlackEarthInc.SI&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'><img alt='Get it on Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png'/></a>
      </div>
    </h1>
  </div>
  <div class="footer text-center" style="color: white">
    ESA/Hubble, NASA, ESO, M. Kornmesser
  </div>
</div>

<div class="section one container-fluid" id="more_information">
  <div class="body">
    <div class="row">
      <div class="col-12 text-center mb-5">
        <h2><strong>Explore The Universe And Its Endless Opportunities</strong></h2>
        <h5>Experience Infinite Possibilities And Freedom As You Grow To Become The Most Powerful Player Ever Known!</h5>
      </div>
      <div class="col-lg-4 offset-lg-2 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Become a Merchant</h5>
          <div class="card-body">
            <h5 class="mb-3">You know the galaxy and its corners like the back of your hand. You make great profit in buying items at one place and selling them at another.</h5>
            <h5 class="mb-5">You may also help other big alliances to move their cargo from one place to another if the price is right.</h5>
            <%= image_tag('home/merchant-home.png', class: 'border-round') %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Become a Miner</h5>
          <div class="card-body">
            <h5 class="mb-3">You have specialized in the different materials of asteroids and know where to get the best price for them.</h5>
            <h5 class="mb-5">You are also on a journey to find the most valuable asteroids ever known to humanity.</h5>
            <%= image_tag('home/mining-home.png', class: 'border-round') %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 offset-lg-2 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Become a Manufacturer</h5>
          <div class="card-body">
            <h5 class="mb-3">You are a skilled craftsman who creates everything that other pilots currently need the most.</h5>
            <h5 class="mb-5">You have come a long way to achieve a very high success rate on even your most powerful creations.</h5>
            <%= image_tag('home/factory-home.gif', class: 'border-round') %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Become a Pirate</h5>
          <div class="card-body">
            <h5 class="mb-3">You are a dangerous person that others don't even want to meet in their darkest dreams.</h5>
            <h5 class="mb-5">You know when to go in for a good catch and when to remain silently in the back.</h5>
            <%= image_tag('home/combat-home.png', class: 'border-round') %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 offset-lg-4 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Become an Explorer</h5>
          <div class="card-body">
            <h5 class="mb-3">You are on a constant lookout for the most valuable goods found in abandoned structures in space.</h5>
            <h5 class="mb-5">You jump from system to system and scan for hidden exploration sites containing lots of treasure.</h5>
            <%= image_tag('home/exploration-home.png', class: 'border-round' ) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer text-center" style="color: black">
    ESO/M. Kornmesser
  </div>
</div>

<div class="section two container-fluid">
  <div class="body">
    <div class="row">
      <div class="col-12 text-center mb-5">
        <h2><strong>100% Community Driven</strong></h2>
        <h5>Be A Part Of An Awesome Community And Help Shaping The Future Of The Game!</h5>
      </div>
      <div class="col-lg-4 offset-lg-2 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Community Polls</h5>
          <div class="card-body">
            <h5 class="mb-3">Every major gameplay / ui change has to be approved by the community in order to get into the game.</h5>
            <h5 class="mb-5">A consent of at least 75 percent is required. The community can also see on what specific poll I am working on at the moment.</h5>
            <%= image_tag('home/polls-home.png', class: 'border-round') %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-3">
        <div class="card black-card">
          <h5 class="card-header text-center">Dedicated Forum</h5>
          <div class="card-body">
            <h5 class="mb-3">Stellar Invictus has its own dedicated forum for its community to discuss every single aspect of the game.</h5>
            <h5 class="mb-5">You can also give new suggestions or ideas for the game which will then result in ingame polls.</h5>
            <%= image_tag('home/forums-home.png', class: 'border-round') %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer text-center" style="color: black">
    NASA, ESA, L. Calçada
  </div>
</div>

app/views/static_pages/map.html.erb
<% if current_user.route != [] %>
  <%= render partial: 'systems/route_card' %>
<% end %>

<div class="card black-card map-card">
  <h5 class="card-header mobile-display-none"><%= I18n.t('navbar.map') %></h5>
  <div class="speech-bubble"></div>
  <div class="card-body" id="map">
    
  </div>
</div>

<style>
  #map {
    overflow: hidden;
    padding: 0;
  }
  
  .speech-bubble {
    z-index: 10;
    display: block;
    top: -1000px;
    left: -1000px;
  	position: absolute;
  	background: #5d5d5d;
  	border-radius: .4em;
  }
  
  .speech-bubble:after {
  	content: '';
  	position: absolute;
  	bottom: 0;
  	left: 50%;
  	width: 0;
  	height: 0;
  	border: 20px solid transparent;
  	border-top-color: #191919;
  	border-bottom: 0;
  	margin-left: -20px;
  	margin-bottom: -20px;
  }
</style>

<script>
    // create an array with nodes
    var nodes = new vis.DataSet([
      <% System.mapdata['systems'].each do |key, val| %>
        {id: <%= key %>, label: "<%= val['faction'] %> <%= val['name'] %>", image: "<%= image_url("planets/star_#{val['security']}.png") %>", font: {<%= "size: 20, color: 'yellow'".html_safe if current_user.system_id == key %>} },
      <% end %>
    ]);

    // create an array with edges
    var edges = new vis.DataSet([
      <% System.mapdata['jumpgates'].each do |key, val| %>
          {id: <%= key %>, from: <%= val['from'] %>, to: <%= val['to'] %>},
      <% end %>
    ]);

    // create a network
    var container = document.getElementById('map');

    // provide the data in the vis format
    var data = {
        nodes: nodes,
        edges: edges
    };
    
    // set options
    var options = {
      autoResize: true,
      height: '600px',
      width: '100%',
      nodes: {
        shape: 'image',
        size: 20,
        fixed: true,
        font: { color: 'white' }
      },
      edges: {
        color: { color: 'grey' },
        selectionWidth: 0
      },
      physics: { enabled: false },
      // Seeds: 626344
      layout: { randomSeed: 576136 },
      interaction: { selectConnectedEdges: false }
    };

    // initialize your network!
    var network = new vis.Network(container, data, options);
    
    // get info from node on select
    network.on("click", function (params) {
      if (params.nodes.length) {
        var id = params.nodes[0]
        var position = network.canvasToDOM(network.getPositions([id])[id])
        
        $.get('system/info', {id: id}, function(data) {
          $('.speech-bubble').html(data);
          setTimeout(function() {
            if ($(window).width() <= 767) {
              $('.speech-bubble').css({position: 'absolute', top: position.y-$('.speech-bubble').height()-30, left: position.x-($('.speech-bubble').width() / 2)}); 
            } else {
              $('.speech-bubble').css({position: 'absolute', top: position.y-$('.speech-bubble').height()+10, left: position.x-($('.speech-bubble').width() / 2)});   
            }
          }, 10)
        }); 
      }
    });
    
    network.on("zoom", function () {
      $('.speech-bubble').css({position: 'absolute', top: -1000, left: -1000, display: 'block'}); 
    });
    
    network.on("dragStart", function () {
      $('.speech-bubble').css({position: 'absolute', top: -1000, left: -1000, display: 'block'}); 
    });
    
    // draw route if user has one
    <% if current_user.route %>
      <% current_user.route.each do |step| %>
        var edge = edges.get(<%= step %>);
        edges.remove(<%= step %>);
        edges.add({id: <%= step %>, from: edge.from, to: edge.to, color: { color: 'red' }, width: 5});
      <% end %>
    <% end %>

    // create route button
    $('.speech-bubble').on('click', '.get-route-btn', function() {
      var id = $(this).data('id');
      var button = $(this);
      var html = $(this).html();
      
      loading_animation($(this));
      
      $.post('system/route', {id: id}, function(data) {
        if ($('.route-card').length) {
          $('.route-card').remove();
        }
        $(data.card).insertBefore($('.map-card'));
        $.each(data.old_route, function(index, value) {
          var edge = edges.get(value);
          edges.remove(value);
          edges.add({id: value, from: edge.from, to: edge.to, color: { color: 'grey' }, width: 1});
        });
        $.each(data.route, function(index, value) {
          var edge = edges.get(value);
          edges.remove(value);
          edges.add({id: value, from: edge.from, to: edge.to, color: { color: 'red' }, width: 5});
        });
        button.html(html);
        $('.speech-bubble').css({position: 'absolute', top: -1000, left: -1000, display: 'block'}); 
      }).fail(function(data) { button.html(html); });
    });
    
    // Jump Drive Btn
    var jump_drive_btn_interval;
    $('.speech-bubble').on('click', '.jump-drive-btn', function() {
      var id = $(this).data('id');
      var button = $(this);
      var html = $(this).html();
      
      loading_animation($(this));
      
      $.post('system/jump_drive', {id: id}, function(data) {
        if (data.traveltime) {
          traveltime = data.traveltime
          button.html(traveltime);
          jump_drive_btn_interval = setInterval(function() {
            traveltime = traveltime - 1
            button.html(traveltime)
            if (traveltime == 0) {
              clearInterval(jump_drive_btn_interval);
            }
          }, 1000)
        }
      }).fail(function(data) { if (data.responseJSON.error_message) { $.notify(data.responseJSON.error_message, {style: 'alert'}); } button.html(html); });
    });
    
    // remove route button
    $('#app-container').on('click', '.remove-route-btn', function(){
      loading_animation($(this));
      $.post('system/clear_route', function(data) {
        $('.route-card').remove();
        $.each(data.route, function(index, value) {
          var edge = edges.get(value);
          edges.remove(value);
          edges.add({id: value, from: edge.from, to: edge.to, color: { color: 'grey' }, width: 1});
        });
      });
    });
</script>

app/views/static_pages/nojs.html.erb
<!-- TODO -->
<div class="card card-body">
    No Javascript detected :(<br>
    Please enable Javascript and reload the page
</div>

app/views/static_pages/support.html.erb
<div class="card black-card">
  <h5 class="card-header"><%= I18n.t('support.submit_support_ticket') %></h5>
  <div class="card-body">
    <%= form_tag create_support_ticket_path do %>
    
      <div class="card card-body text-white bg-secondary mb-3">
        <span>Need to upload a screenshot? Use <a href="https://puush.me/" target="_blank" class="color-sec-medium">Puush</a></span>  
      </div>
    
      <div class="field mb-3">
        <label><%= I18n.t('support.category') %></label>
        <%= select_tag 'ticket[category]', options_for_select(["Account", "Gameplay", "Technical", "Player Report"], "Account"), class: 'form-control' %>
      </div>
    
      <div class="field mb-3">
        <label><%= I18n.t('support.username') %></label>
        <%= text_field_tag 'ticket[username]', current_user.full_name, class: 'form-control', disabled: true %>
      </div>
      
      <div class="field mb-3">
        <label><%= I18n.t('support.subject') %></label>
        <%= text_field_tag 'ticket[subject]', nil, class: 'form-control' %>
      </div>
      
      <div class="field mb-3">
        <label><%= I18n.t('support.description') %></label>
        <%= text_area_tag 'ticket[description]', nil, class: 'form-control', style: 'height: 200px' %>
      </div>
      
      <%= submit_tag 'submit', :value => I18n.t('support.submit'), class: 'btn btn-outline-primary', id: 'support-ticket-submit-btn' %>
    <% end %>
  </div>
</div>