config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'connect', sign_out: 'disconnect', sign_up: 'enlist', edit: 'pilot' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  # Static Pages
  root 'static_pages#home'
  get '/credits', to: 'static_pages#credits'
  get '/nojs', to: 'static_pages#nojs'
  get '/support', to: 'static_pages#support'
  get '/donate', to: 'static_pages#donate'
  post '/support_ticket/create', to: 'static_pages#create_support_ticket', as: :create_support_ticket

  # Factions
  resources :factions, only: [:index]
  scope :factions do
    post 'choose', to: 'factions#choose_faction', as: :choose_faction
  end

  # Game
  get '/game', to: 'game#index'
  scope :game do
    post 'warp', to: 'game#warp'
    post 'jump', to: 'game#jump'
    get 'local_players', to: 'game#local_players'
    get 'ship_info', to: 'game#ship_info'
    get 'player_info', to: 'game#player_info'
    get 'chat', to: 'game#chat'
    get 'system_card', to: 'game#system_card'
    get 'locations_card', to: 'game#locations_card'
  end

  # User
  scope :user do
    get 'info/:id', to: 'users#info'
    post 'update_bio', to: 'users#update_bio'
    post 'place_bounty', to: 'users#place_bounty'
  end

  # Mails
  resources :game_mails, only: [:index, :new, :create, :show], path: 'mails'

  # Station
  scope :stations do
    post 'dock', to: 'stations#dock'
    post 'undock', to: 'stations#undock'
    post 'buy', to: 'stations#buy'
    post 'store', to: 'stations#store'
    post 'load', to: 'stations#load'
    post 'dice_roll', to: 'stations#dice_roll'
  end
  get '/station', to: 'stations#index'

  # Map
  get '/map', to: 'static_pages#map'

  # Assets
  get '/assets', to: 'game#assets'

  # Ships
  scope :ship do
    post 'activate', to: 'ships#activate'
    post 'target', to: 'ships#target'
    post 'untarget', to: 'ships#untarget'
    get 'cargohold', to: 'ships#cargohold'
    post 'eject_cargo', to: 'ships#eject_cargo'
    get 'info', to: 'ships#info'
    post 'insure', to: 'ships#insure'
    post 'custom_name', to: 'ships#custom_name'
    get 'upgrade_modal', to: 'ships#upgrade_modal'
    post 'upgrade', to: 'ships#upgrade'
  end

  # Asteroids
  scope :asteroid do
    post 'mine', to: 'asteroids#mine'
    post 'stop_mine', to: 'asteroids#stop_mine'
  end

  # NPCs
  scope :npc do
    post 'target', to: 'npcs#target'
    post 'untarget', to: 'npcs#untarget'
  end

  # Structures
  scope :structure do
    post 'open_container', to: 'structures#open_container'
    post 'pickup_cargo', to: 'structures#pickup_cargo'
    post 'attack', to: 'structures#attack'
    post 'abandoned_ship', to: 'structures#abandoned_ship'
    get 'monument_info', to: 'structures#monument_info'
  end

  # Friends
  get 'friends', to: 'friends#index'
  scope :friends do
    post 'add_friend', to: 'friends#add_friend'
    post 'accept_request', to: 'friends#accept_request'
    post 'remove_friend', to: 'friends#remove_friend'
    post 'search', to: 'friends#search'
  end

  # Chat
  scope :chat do
    post 'join', to: 'chat_rooms#join'
    post 'create', to: 'chat_rooms#create'
    post 'leave', to: 'chat_rooms#leave'
    post 'start_conversation', to: 'chat_rooms#start_conversation'
    post 'search', to: 'chat_rooms#search'
  end

  # Fleets
  scope :fleet do
    post 'invite', to: 'fleets#invite'
    post 'accept_invite', to: 'fleets#accept_invite'
    post 'remove', to: 'fleets#remove'
  end

  # Equipment
  scope :equipment do
    post 'update', to: 'equipment#update'
    post 'switch', to: 'equipment#switch'
    get 'info', to: 'equipment#info'
  end

  # Market
  scope :market do
    get 'list', to: 'market#list'
    get 'search', to: 'market#search'
    post 'buy', to: 'market#buy'
    post 'appraisal', to: 'market#appraisal'
    post 'sell', to: 'market#sell'
    get 'my_listings', to: 'market#my_listings'
    post 'delete_listing', to: 'market#delete_listing'
    post 'create_buy', to: 'market#create_buy'
    post 'fulfill_buy', to: 'market#fulfill_buy'
  end

  # Systems
  scope :system do
    get 'info', to: 'systems#info'
    post 'route', to: 'systems#route'
    post 'clear_route', to: 'systems#clear_route'
    post 'scan', to: 'systems#scan'
    post 'directional_scan', to: 'systems#directional_scan'
    post 'jump_drive', to: 'systems#jump_drive'
  end

  # Missions
  scope :mission do
    get 'info', to: 'missions#info'
    post 'accept', to: 'missions#accept'
    post 'finish', to: 'missions#finish'
    get 'popup', to: 'missions#popup'
    post 'abort', to: 'missions#abort'
  end

  # Blueprints
  scope :blueprint do
    post 'buy', to: 'blueprints#buy'
    get 'modal', to: 'blueprints#modal'
  end

  # Factory
  scope :factory do
    get 'modal', to: 'factories#modal'
    post 'craft', to: 'factories#craft'
    get 'dismantle_modal', to: 'factories#dismantle_modal'
    post 'dismantle', to: 'factories#dismantle'
  end

  # Corporation
  resources :corporations, only: [:index, :new, :create], path: 'corporation'
  scope :corporation do
    post 'update_motd', to: 'corporations#update_motd'
    post 'update_corporation', to: 'corporations#update_corporation'
    post 'kick_user', to: 'corporations#kick_user'
    get 'change_rank_modal', to: 'corporations#change_rank_modal'
    post 'change_rank', to: 'corporations#change_rank'
    post 'deposit_credits', to: 'corporations#deposit_credits'
    post 'withdraw_credits', to: 'corporations#withdraw_credits'
    get 'info', to: 'corporations#info'
    get 'apply_modal', to: 'corporations#apply_modal'
    post 'apply', to: 'corporations#apply'
    post 'accept_application', to: 'corporations#accept_application'
    post 'reject_application', to: 'corporations#reject_application'
    post 'disband', to: 'corporations#disband'
    post 'search', to: 'corporations#search'
    get 'sort_roster', to: 'corporations#sort_roster'
  end

  # Community
  scope :community do
    get '/', to: 'communities#index', as: :community
  end

  # Discourse
  get 'discourse/sso' => 'discourse_sso#sso'

  # Admin
  scope :admin do
    get '/', to: 'admin#index', as: :admin
    post 'search', to: 'admin#search'
    post 'teleport', to: 'admin#teleport'
    post 'set_credits', to: 'admin#set_credits'
    post 'ban', to: 'admin#ban'
    post 'unban', to: 'admin#unban'
    post 'server_message', to: 'admin#server_message'
    post 'mute', to: 'admin#mute'
    post 'unmute', to: 'admin#unmute'
    post 'delete_chat', to: 'admin#delete_chat'
  end

  # Polls
  scope :poll do
    post 'create', to: 'polls#create'
    post 'upvote', to: 'polls#upvote'
    post 'downvote', to: 'polls#downvote'
    post 'move_up', to: 'polls#move_up'
    post 'delete', to: 'polls#delete'
  end

  # ActionCable
  mount ActionCable.server => '/cable'

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    get_local_users
    raise RedirectRequest.new(station_path) if current_user.docked?

    @ship_vars = current_user.active_spaceship&.get_attributes
  end

  def warp
    check_police
    check_warp_disrupt

    raise InvalidRequest if current_user.in_warp? || !(params[:id] || params[:uid])
    align_time = nil
    ship = current_user.active_spaceship

    if params[:id]
      location = Location.ensure(params[:id])
      raise InvalidRequest if location&.system_id != current_user.system_id
      align = ship.get_align_time

      # Fleet Warp
      if params[:fleet] && current_user.fleet
        fleet_members_in_system = current_user.fleet.users.where(system: current_user.system)
        align = fleet_members_in_system.map { |p| p.active_spaceship&.get_align_time }.compact.max

        fleet_members_in_system.each do |user|
          if !user.in_warp?
            WarpWorker.perform_async(user.id, location.id, 0, 0, false, align)
            align_time = (user.active_spaceship.warp_target_id == location.id) ? 0 : align
            user.broadcast(:fleet_warp, location: location.id, align_time: align_time) if user != current_user
          end
        end
      else
        WarpWorker.perform_async(current_user.id, location.id)
      end
      align_time = (ship.warp_target_id == location.id) ? 0 : align

    elsif params[:uid]
      user = User.ensure(params[:uid])
      raise InvalidRequest unless user
      raise InvalidRequest unless user.in_same_fleet_as(current_user)

      # Check location
      raise InvalidRequest.new('errors.user_must_be_in_same_system') unless user.system == current_user.system
      raise InvalidRequest.new('errors.already_at_location') if user.location == current_user.location

      WarpWorker.perform_async(current_user.id, user.location.id)
      align_time = (ship.warp_target_id == user.location.id) ? 0 : ship.get_align_time
    end

    render json: { align_time: align_time }, status: :ok
  end

  def jump
    check_police
    check_warp_disrupt
    raise InvalidRequest if current_user.in_warp? || !(current_user.location.jumpgate || current_user.location.wormhole?)

    JumpWorker.perform_async(current_user.id)

    render json: {}, status: :ok
  end

  def local_players
    get_local_users
    render partial: 'players', locals: { local_users: @local_users }
  end

  def ship_info
    render partial: 'ship_info', locals: { ship_vars: current_user.active_spaceship&.get_attributes }
  end

  def player_info
    render partial: 'player_info'
  end

  def assets
    var1 = Item.where(user: current_user, spaceship: nil, structure: nil).select(:location_id).distinct.pluck(:location_id)
    var2 = Spaceship.where(user: current_user).select(:location_id).distinct.pluck(:location_id)
    @locations = (var1 + var2).uniq
  end

  def chat
    cur_system = current_user.system
    @system_users = User.is_online.where(system: cur_system)
    @local_messages = ChatMessage.includes(:user).where(chat_room: ChatRoom.local.where(system: cur_system).first).last(10)
    @global_messages = ChatMessage.includes(:user).where(chat_room: ChatRoom.global).last(10)

    if params[:popup]
      render partial: 'game/chat_popup', locals: { local_messages: @local_messages, system_users: @system_users, global_messages: @global_messages }
    else
      render partial: 'game/chat', locals: { local_messages: @local_messages, system_users: @system_users, global_messages: @global_messages }
    end
  end

  def system_card
    render partial: 'game/system_card' unless current_user.docked?
  end

  def locations_card
    render partial: 'game/locations' unless current_user.docked?
  end

  private

  def get_local_users
    @local_users ||= User.includes(:faction).is_online.where(location: current_user.location, in_warp: false, docked: false)
  end

  def check_police
    raise InvalidRequest.new('errors.police_inbound') if Npc.police.targeting_user(current_user).exists?
  end

  def check_warp_disrupt
    raise InvalidRequest.new('errors.warp_disrupted') if current_user.active_spaceship&.is_warp_disrupted?
  end
end

app/views/game/_chat.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" data-target="#local-chat" href="#0" role="tab"><%= I18n.t('chat.local') %> (<span id="system-player-count"><%= @system_users.count rescue 0 %></span>)</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" data-target="#global-chat" href="#0" role="tab"><%= I18n.t('chat.global') %></a>
  </li>
  <% if current_user.corporation %>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" data-target="#chatroom-<%= current_user.corporation.chat_room.identifier %>" href="#0" role="tab"><%= I18n.t('chat.corporation') %></a>
    </li>
  <% end %>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" data-target="#log" href="#0" role="tab"><%= I18n.t('chat.log') %></a>
  </li>
  <% if current_user.chat_rooms.present? %>
    <% current_user.chat_rooms.each do |room| %>
      <% if room.custom? %>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" data-target="#chatroom-<%= room.identifier %>" href="#0" role="tab">
            <%= room.title %>&nbsp;&nbsp;
            <button class="btn btn-outline-danger close-chat-btn" style="padding: 0rem 0.3rem;line-height: 1.3;" data-id="<%= room.identifier %>">
              <i class="fa fa-times fa-sm">
            </i></button>
          </a>
        </li>
      <% end %>
    <% end %>
  <% end %>
  <button class="btn btn-outline-primary btn-sm mt-5px" data-toggle="modal" data-target="#join-chatroom-modal">
    <i class="fa fa-plus"></i>
  </button>
</ul>
<div class="tab-content">
  <div class="tab-pane fade show active" id="local-chat" role="tabpanel">
    <div class="row">
      <div class="col-lg-10">
        <table class="table table-striped table-bordered">
          <tbody>

          </tbody>
        </table>
      </div>
      <div class="col-lg-2">
        <div class="outer" id="system-players">
          <% map_and_sort(system_users).each do |key, value| %>
            <div>
              <a class='player-modal' href="#" data-id="<%= value %>"><%= key %></a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="global-chat" role="tabpanel">
    <table class="table table-striped table-bordered mt-5px">
      <tbody>
        <% global_messages.each do |msg| %>
          <%= render partial: 'chat_messages/message', locals: { message: msg } %>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if current_user.corporation %>
    <div class="tab-pane fade corporation-chat" id="chatroom-<%= current_user.corporation.chat_room.identifier %>" role="tabpanel">
      <div class="row">
        <div class="col-lg-10">
          <table class="table table-striped table-bordered">
            <tbody>
              <% current_user.corporation.chat_room.chat_messages.includes(:user).last(20).each do |msg| %>
                <%= render partial: 'chat_messages/message', locals: { message: msg } %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-lg-2">
          <div class="outer" id="chatroom-<%= current_user.corporation.chat_room.identifier %>-players">
            <% map_and_sort(current_user.corporation.chat_room.users.where("online > 0")).each do |key, value| %>
              <div>
                <a class='player-modal' href="#" data-id="<%= value %>"><%= key %></a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="tab-pane fade" id="log" role="tabpanel">
    <table class="table table-striped table-bordered mt-5px">
      <tbody>
      </tbody>
    </table>
  </div>
  <% if current_user.chat_rooms.present? %>
    <% current_user.chat_rooms.includes(:fleet).each do |room| %>
      <% if room.custom? %>
        <div class="tab-pane fade custom-chat" id="chatroom-<%= room.identifier %>" role="tabpanel">
          <div class="row">
            <div class="col-lg-10">
              <table class="table table-striped table-bordered">
                <tbody>
                  <% room.chat_messages.includes(:user).last(20).each do |msg| %>
                    <%= render partial: 'chat_messages/message', locals: { message: msg } %>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div class="col-lg-2">
              <div class="w-100 mt-5px">
                <span>ID: <%= room.identifier %></span>
                <a class="btn btn-outline-primary btn-sm float-right p-0-5 text-primary invite-to-chatroom-btn" data-toggle="modal" data-target="#add-to-chat-modal" href="#0" data-identifier="<%= room.identifier %>"><i class="fa fa-plus"></i></a>
              </div>
              <div class="outer" id="chatroom-<%= room.identifier %>-players">
                <% map_and_sort(room.users.where("online > 0")).each do |key, value| %>
                  <div class="pt-2px">
                    <a class='player-modal' href="#" data-id="<%= value %>">
                      <span class="<%= User.find(value).active_spaceship.get_hp_color if room.fleet %>"><%= key %></span>
                      <% if room.fleet %>
                        <a class="btn btn-outline-primary btn-xs warp-btn float-right p-0-5 text-primary" data-uid="<%= value %>"><i class='fa fa-angle-double-right'></i></a>
                      <% end %>
                    </a>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div class="input-group">
    <input type="text" class="form-control" id="chat_msg" placeholder="Message" maxlength="300" autocomplete="off">
    <div class="input-group-append">
      <button class="btn btn-outline-secondary" type="button" id="chat_send"><%= I18n.t('chat.send') %></button>
    </div>
  </div>
</div>

<!-- Join Chat Room Modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="join-chatroom-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= I18n.t('chat.join_create_room') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><strong><%= I18n.t('chat.join_room') %></strong></p>
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="join-chatroom-modal-join-input" placeholder="<%= I18n.t('chat.room_id') %>">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="button" id="join-chatroom-modal-join-btn"><%= I18n.t('chat.join') %></button>
          </div>
        </div>
        <p><strong><%= I18n.t('chat.create_room') %></strong></p>
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="join-chatroom-modal-create-input" placeholder="<%= I18n.t('chat.room_name') %>">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="button" id="join-chatroom-modal-create-btn"><%= I18n.t('chat.create') %></button>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Search Users Modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="add-to-chat-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= I18n.t('chat.invite_user_to_join_room') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="add-friend-modal-body">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="<%= I18n.t('search.user_name') %>" id="add-to-chat-modal-input">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="button" id="add-to-chat-modal-search-btn"><%= I18n.t('search.search') %></button>
          </div>
        </div>
        <div id="add-to-chat-modal-result">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= I18n.t('modal.close') %></button>
      </div>
    </div>
  </div>
</div>


<!-- Chat Rooms JS -->
<script>
  <% if current_user&.chat_rooms.present? %>
    <% current_user.chat_rooms.each do |room| %>
      if (!App['chatroom-<%= room.identifier %>']) {
        App['chatroom-<%= room.identifier %>'] = App.cable.subscriptions.create({
          channel: 'ChatChannel',
          room: 'chatroom-<%= room.identifier %>'
        }, {
          received: function(data) {
            if (data.message) {
              if ($('#chatroom-<%= room.identifier %>').length > 0) {
                $('#chatroom-<%= room.identifier %> table tbody').append(data.message);
                if (!$('a[data-target="#chatroom-<%= room.identifier %>"]').hasClass('active')) {
                  $('a[data-target="#chatroom-<%= room.identifier %>"]').addClass('chat-flash');
                  setFlashChats();
                }
                return scrollChats();
              }
            }
            else if (data.method == 'update_players' && data.names) {
              update_players_in_custom_chat("chatroom-<%= room.identifier %>",data.names,data.fleet,data.color);
            }
            else if (data.method == 'player_appeared' && ('.players-card').length) {
              reload_players_card();
            }
            else if (data.method == 'update_hp_color' && data.color && data.id) {
              update_hp_color("chatroom-<%= room.identifier %>",data.color,data.id)
            }
          },
          send_message: function(message) {
            return this.perform('send_message', {
              message: message,
              room: 'chatroom-<%= room.identifier %>'
            });
          }
        });
      }
    <% end %>
  <% end %>
</script>

app/views/game/_chat_popup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar Invictus Chat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="pragma" content="no-cache" />
    <link rel="icon"type="image/png" href="/favicon.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-permanent': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  </head>

  <body style="padding-bottom:0px;">

    <div id="app-container">

      <div class="card black-card chat-card popup">
        <h5 class="card-header">
          <%= I18n.t('game.chat') %>
        </h5>
        <div class="card-body">
          <%= render partial: 'game/chat', locals: {local_messages: @local_messages, system_users: @system_users, global_messages: @global_messages} %>
        </div>
      </div>

      <%= render 'layouts/modals' %>
    </div>

  </body>

  <script>
    var logged_in = <%= !current_user&.faction.nil? %>
  </script>
</html>

app/views/game/_location.html.erb
<tr class="<%= 'color-yellow' if location.jumpgate? && current_user.route.include?(location.jumpgate.id.to_s) %> <%= 'hidden-site' if location.hidden %>">
  <td><%= image_tag("icons/#{location.location_type}.png") %></td>
  <td class="name"><%= location.get_name %></td>
  <td><%= I18n.t("types.#{location.location_type}") %></td>
  <td>
    <button class="btn btn-outline-primary btn-sm warp-btn", data-id="<%= location.id %>"><i class='fa fa-angle-double-right'></i></button>
    <% if current_user.fleet %>
      <button class="btn btn-outline-info btn-sm warp-btn" data-id="<%= location.id %>" data-fleet="true"><i class='fa fa-angle-double-right'></i></button>
    <% end %>
  </td>
</tr>

app/views/game/_location_info.html.erb
<% # This makes no sense... if (jumpgate? || wormhole?) && jumpgate? %>
<% if (current_user.location.jumpgate? || current_user.location.wormhole?) && current_user.location.jumpgate? %>
  <tr class="<%= 'color-yellow' if current_user.route.include?(current_user.location.jumpgate.id.to_s) %>">
    <td><%= image_tag('icons/jumpgate.png') %></td>
    <td class="name"><%= current_user.location.get_name %></td>
    <td><%= I18n.t('overview.jumpgate') %></td>
    <td class="mobile-display-none"></td>
    <td>
      <button class="btn btn-outline-primary btn-xs jumpgate-jump-btn w-100" data-time="<%= current_user.location.jumpgate.traveltime %>">
        <%= I18n.t('actions.jump') %>
      </button>
    </td>
  </tr>
<% elsif current_user.location.asteroids.present? %>
  <% current_user.location.asteroids.each do |asteroid| %>
    <tr>
      <td><%= image_tag('icons/asteroid.png') %></td>
      <td class="name"><%= I18n.t('overview.asteroid') %> <span class="mobile-display-none">(<%= asteroid.asteroid_type.capitalize %>)</span></td>
      <td><%= asteroid.asteroid_type.capitalize %></td>
      <td class="mobile-display-none"></td>
      <td>
        <button class="btn btn-outline-primary btn-xs w-100 mine-asteroid-btn" data-id="<%= asteroid.id %>">
          <%= I18n.t('actions.mine') %>
        </button>
      </td>
    </tr>
  <% end %>
<% elsif current_user.location.station? %>
  <tr>
    <td><%= image_tag('icons/station.png') %></td>
    <td class="name"><%= current_user.location.get_name %></td>
    <td><%= I18n.t('overview.station') %></td>
    <td class="mobile-display-none"><%= current_user.location.faction.get_ticker if current_user.location.faction %></td>
    <td>
      <button class="btn btn-outline-primary btn-xs station-dock-btn w-100">
        <%= I18n.t('actions.dock') %>
      </button>
    </td>
  </tr>
<% end %>

app/views/game/_locations.html.erb
<div class="card black-card overview-card">
  <h5 class="card-header">
    <%= I18n.t('game.locations') %>
    <a data-toggle="collapse" data-target="#collapse-locations" href="#0" class="float-right">
      <div class="btn btn-xs btn-outline-primary p-0-5 ml-1"><i class="fa fa-arrow-down"></i></div>
    </a>
    <% if current_user.active_spaceship.get_scanner_range > 0 %>
      <button class="btn btn-sm btn-outline-primary float-right scan-system-btn progress-btn" style="padding: 0 1rem;margin-left:5px;">
        <span class="content" style="font-size: 14px;"><%= I18n.t('equipment.scan') %></span>
        <span class="loader">
          <span class="loader-inner"></span>
        </span>
      </button>
    <% end %>
    <% if current_user.active_spaceship.get_directional_scanner %>
      <button class="btn btn-sm btn-outline-primary float-right directional-scan-btn" style="padding: 0 1rem;margin-left:5px;"><span style="font-size: 14px;">D</span></button>
    <% end %>
    <%= link_to I18n.t('navbar.map'), map_path, class: "btn btn-sm btn-outline-primary float-right mr-5px", style: "padding: 0 1rem;font-size: 14px;" %>
  </h5>
  <div class="collapse show" id="collapse-locations">
    <div class="card-body">
      <%= render partial: 'game/locations_table', locals: {locations: current_user.system.locations.not_hidden.includes(mission: :user)} %>
    </div>
  </div>
</div>

app/views/game/_locations_table.html.erb
<table class="table table-striped table-bordered table-sm">
  <thead>
    <tr>
      <th id="img-td"></td>
      <th>Name</td>
      <th style="width:100px"><%= I18n.t('game.type') %></td>
      <th id="btn-td" style="<%= 'width:73px' if current_user.fleet %>"></td>
    </tr>
  </thead>
  <tbody>
    <% locations.each do |location|
         next if !location.scan_visible?(current_user) %>
      <%= render partial: 'game/location', locals: {location: location} %>
    <% end %>
  </tbody>
</table>