config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'connect', sign_out: 'disconnect', sign_up: 'enlist', edit: 'pilot' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  # Static Pages
  root 'static_pages#home'
  get '/credits', to: 'static_pages#credits'
  get '/nojs', to: 'static_pages#nojs'
  get '/support', to: 'static_pages#support'
  get '/donate', to: 'static_pages#donate'
  post '/support_ticket/create', to: 'static_pages#create_support_ticket', as: :create_support_ticket

  # Factions
  resources :factions, only: [:index]
  scope :factions do
    post 'choose', to: 'factions#choose_faction', as: :choose_faction
  end

  # Game
  get '/game', to: 'game#index'
  scope :game do
    post 'warp', to: 'game#warp'
    post 'jump', to: 'game#jump'
    get 'local_players', to: 'game#local_players'
    get 'ship_info', to: 'game#ship_info'
    get 'player_info', to: 'game#player_info'
    get 'chat', to: 'game#chat'
    get 'system_card', to: 'game#system_card'
    get 'locations_card', to: 'game#locations_card'
  end

  # User
  scope :user do
    get 'info/:id', to: 'users#info'
    post 'update_bio', to: 'users#update_bio'
    post 'place_bounty', to: 'users#place_bounty'
  end

  # Mails
  resources :game_mails, only: [:index, :new, :create, :show], path: 'mails'

  # Station
  scope :stations do
    post 'dock', to: 'stations#dock'
    post 'undock', to: 'stations#undock'
    post 'buy', to: 'stations#buy'
    post 'store', to: 'stations#store'
    post 'load', to: 'stations#load'
    post 'dice_roll', to: 'stations#dice_roll'
  end
  get '/station', to: 'stations#index'

  # Map
  get '/map', to: 'static_pages#map'

  # Assets
  get '/assets', to: 'game#assets'

  # Ships
  scope :ship do
    post 'activate', to: 'ships#activate'
    post 'target', to: 'ships#target'
    post 'untarget', to: 'ships#untarget'
    get 'cargohold', to: 'ships#cargohold'
    post 'eject_cargo', to: 'ships#eject_cargo'
    get 'info', to: 'ships#info'
    post 'insure', to: 'ships#insure'
    post 'custom_name', to: 'ships#custom_name'
    get 'upgrade_modal', to: 'ships#upgrade_modal'
    post 'upgrade', to: 'ships#upgrade'
  end

  # Asteroids
  scope :asteroid do
    post 'mine', to: 'asteroids#mine'
    post 'stop_mine', to: 'asteroids#stop_mine'
  end

  # NPCs
  scope :npc do
    post 'target', to: 'npcs#target'
    post 'untarget', to: 'npcs#untarget'
  end

  # Structures
  scope :structure do
    post 'open_container', to: 'structures#open_container'
    post 'pickup_cargo', to: 'structures#pickup_cargo'
    post 'attack', to: 'structures#attack'
    post 'abandoned_ship', to: 'structures#abandoned_ship'
    get 'monument_info', to: 'structures#monument_info'
  end

  # Friends
  get 'friends', to: 'friends#index'
  scope :friends do
    post 'add_friend', to: 'friends#add_friend'
    post 'accept_request', to: 'friends#accept_request'
    post 'remove_friend', to: 'friends#remove_friend'
    post 'search', to: 'friends#search'
  end

  # Chat
  scope :chat do
    post 'join', to: 'chat_rooms#join'
    post 'create', to: 'chat_rooms#create'
    post 'leave', to: 'chat_rooms#leave'
    post 'start_conversation', to: 'chat_rooms#start_conversation'
    post 'search', to: 'chat_rooms#search'
  end

  # Fleets
  scope :fleet do
    post 'invite', to: 'fleets#invite'
    post 'accept_invite', to: 'fleets#accept_invite'
    post 'remove', to: 'fleets#remove'
  end

  # Equipment
  scope :equipment do
    post 'update', to: 'equipment#update'
    post 'switch', to: 'equipment#switch'
    get 'info', to: 'equipment#info'
  end

  # Market
  scope :market do
    get 'list', to: 'market#list'
    get 'search', to: 'market#search'
    post 'buy', to: 'market#buy'
    post 'appraisal', to: 'market#appraisal'
    post 'sell', to: 'market#sell'
    get 'my_listings', to: 'market#my_listings'
    post 'delete_listing', to: 'market#delete_listing'
    post 'create_buy', to: 'market#create_buy'
    post 'fulfill_buy', to: 'market#fulfill_buy'
  end

  # Systems
  scope :system do
    get 'info', to: 'systems#info'
    post 'route', to: 'systems#route'
    post 'clear_route', to: 'systems#clear_route'
    post 'scan', to: 'systems#scan'
    post 'directional_scan', to: 'systems#directional_scan'
    post 'jump_drive', to: 'systems#jump_drive'
  end

  # Missions
  scope :mission do
    get 'info', to: 'missions#info'
    post 'accept', to: 'missions#accept'
    post 'finish', to: 'missions#finish'
    get 'popup', to: 'missions#popup'
    post 'abort', to: 'missions#abort'
  end

  # Blueprints
  scope :blueprint do
    post 'buy', to: 'blueprints#buy'
    get 'modal', to: 'blueprints#modal'
  end

  # Factory
  scope :factory do
    get 'modal', to: 'factories#modal'
    post 'craft', to: 'factories#craft'
    get 'dismantle_modal', to: 'factories#dismantle_modal'
    post 'dismantle', to: 'factories#dismantle'
  end

  # Corporation
  resources :corporations, only: [:index, :new, :create], path: 'corporation'
  scope :corporation do
    post 'update_motd', to: 'corporations#update_motd'
    post 'update_corporation', to: 'corporations#update_corporation'
    post 'kick_user', to: 'corporations#kick_user'
    get 'change_rank_modal', to: 'corporations#change_rank_modal'
    post 'change_rank', to: 'corporations#change_rank'
    post 'deposit_credits', to: 'corporations#deposit_credits'
    post 'withdraw_credits', to: 'corporations#withdraw_credits'
    get 'info', to: 'corporations#info'
    get 'apply_modal', to: 'corporations#apply_modal'
    post 'apply', to: 'corporations#apply'
    post 'accept_application', to: 'corporations#accept_application'
    post 'reject_application', to: 'corporations#reject_application'
    post 'disband', to: 'corporations#disband'
    post 'search', to: 'corporations#search'
    get 'sort_roster', to: 'corporations#sort_roster'
  end

  # Community
  scope :community do
    get '/', to: 'communities#index', as: :community
  end

  # Discourse
  get 'discourse/sso' => 'discourse_sso#sso'

  # Admin
  scope :admin do
    get '/', to: 'admin#index', as: :admin
    post 'search', to: 'admin#search'
    post 'teleport', to: 'admin#teleport'
    post 'set_credits', to: 'admin#set_credits'
    post 'ban', to: 'admin#ban'
    post 'unban', to: 'admin#unban'
    post 'server_message', to: 'admin#server_message'
    post 'mute', to: 'admin#mute'
    post 'unmute', to: 'admin#unmute'
    post 'delete_chat', to: 'admin#delete_chat'
  end

  # Polls
  scope :poll do
    post 'create', to: 'polls#create'
    post 'upvote', to: 'polls#upvote'
    post 'downvote', to: 'polls#downvote'
    post 'move_up', to: 'polls#move_up'
    post 'delete', to: 'polls#delete'
  end

  # ActionCable
  mount ActionCable.server => '/cable'

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.friendships.where(accepted: true)
    @pending = Friendship.where('friend_id = ? OR user_id = ?', current_user.id, current_user.id).where(accepted: false)
  end

  def add_friend
    friend = User.ensure(params[:id])
    raise InvalidRequest if !friend || (friend == current_user) || current_user.friendships.where(friend: friend).exists?

    if (request = friend.friendships.is_request.where(friend: current_user).first)
      raise InvalidRequest if !accept_friendship(request)
    else
      # Create Request
      Friendship.create(user: current_user, friend: friend, accepted: false)
      friend.broadcast(:notify_info,
        text: I18n.t('notification.received_friend_request', user: current_user.full_name)
      )
    end

    render json: {}, status: :ok
  end

  def accept_request
    raise InvalidRequest unless accept_friendship(params[:id])
    render json: {}, status: :ok
  end

  def remove_friend
    friend = User.ensure(params[:id])
    raise InvalidRequest unless friend

    if (found_friend = current_user.friends.where(id: friend.id))
      current_user.friends.destroy(found_friend)
    else
      Friendship.where(user: friend, friend: current_user).first&.destroy
    end
    render json: {}, status: :ok
  end

  def search
    raise InvalidRequest unless params[:name]
    result = User.where('full_name ILIKE ?', "%#{params[:name]}%").where.not(faction_id: nil).first(20)
    render partial: 'friends/search', locals: { users: result }
  end

  private

  def accept_friendship(friendship)
    friendship = Friendship.ensure(friendship)
    return false if !friendship || friendship.user == current_user || friendship.friend != current_user || friendship.accepted?

    friendship.update(accepted: true)
    # make the reverse friendship record
    Friendship.create(user: friendship.friend, friend: friendship.user, accepted: true)
  end
end

app/views/friends/_friends.html.erb
<table class="table table-striped table-bordered">
  <tbody>
    <% if @friends.present? %>
      <% @friends.each do |friendship| %>
        <% if friendship.user == current_user %>
          <tr>
            <td>
              <%= image_tag(friendship.friend_avatar_url, class: 'float-left') %>
              <div class="float-right">
                <button class="btn btn-outline-danger remove-as-friend-btn btn-sm" data-id="<%= friendship.friend_id %>">
                  <i class="fa fa-times"></i>
                </button>
                <%= link_to "<i class='fa fa-comment-alt'></i>".html_safe, new_game_mail_path(to: friendship.friend_full_name), class: 'btn btn-outline-primary btn-sm', data: {toggle: 'tooltip', placement: 'top'}, title: I18n.t('tooltips.message') %>
              </div>
              <a href="#" class="player-modal" data-id=<%= friendship.friend_id %>><strong><%= friendship.friend_full_name %></strong></a><br>
              <%= online_status(friendship.friend) %> - <strong class="color-sec-<%= friendship.friend.system.security_status %>"><%= friendship.friend.system.name %></strong> <%= friendship.friend.location.get_name %>
            </td>
          </tr>
        <% else %>
          <tr>
            <td>
              <%= image_tag(friendship.user_avatar_url, class: 'float-left') %>
              <div class="float-right">
                <button class="btn btn-outline-danger remove-as-friend-btn btn-sm" data-id="<%= friendship.user_id %>">
                  <i class="fa fa-times"></i>
                </button>
                <%= link_to "<i class='fa fa-comment-alt'></i>".html_safe, new_game_mail_path(to: friendship.user.full_name), class: 'btn btn-outline-primary btn-sm', data: {toggle: 'tooltip', placement: 'top'}, title: I18n.t('tooltips.message') %>
              </div>
              <a href="#" class="player-modal" data-id=<%= friendship.user_id %>><strong><%= friendship.user.full_name %></strong></a><br>
              <%= online_status(friendship.user) %> - <strong class="color-sec-<%= friendship.user.system.security_status %>"><%= friendship.user.system.name %></strong> <%= friendship.user.location.get_name %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center"><span><strong><%= I18n.t('friends.dont_be_lonely') %></strong></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/_pending.html.erb
<table class="table table-striped table-bordered">
  <tbody>
    <% pending.each do |friendship| %>
      <% if friendship.friend == current_user %>
        <tr>
          <td>
            <%= image_tag(friendship.user_avatar_url, class: 'float-left') %>
            <div class="float-right">
              <button class="btn btn-outline-success accept-friend-request-btn btn-sm" data-id="<%= friendship.id %>">
                <i class="fa fa-plus"></i>
              </button>
              <button class="btn btn-outline-danger remove-as-friend-btn btn-sm" data-id="<%= friendship.user_id %>">
                <i class="fa fa-times"></i>
              </button>
            </div>
            <a href="#" class="player-modal" data-id=<%= friendship.user_id %>><strong><%= friendship.user.full_name %></strong></a><br>
            <%= online_status(friendship.user) %>
          </td>
        </tr>
      <% else %>
        <tr>
          <td>
            <%= image_tag(friendship.friend_avatar_url, class: 'float-left') %>
            <div class="float-right">
              <button class="btn btn-outline-danger remove-as-friend-btn btn-sm" data-id="<%= friendship.friend_id %>">
                <i class="fa fa-times"></i>
              </button>
            </div>
            <a href="#" class="player-modal" data-id=<%= friendship.friend_id %>><strong><%= friendship.friend_full_name %></strong></a><br>
            <%= online_status(friendship.friend) %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/friends/_search.html.erb
<% not_current_user = user != current_user %>
<table class="table table-striped table-bordered friends-search-table">
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= image_tag("avatars/#{user.avatar}.jpg", class: 'float-left') %>
          <div class="float-right">
            <% if current_user.friends.where(id: user.id).empty? && not_current_user %>
              <button class="btn btn-outline-primary search-add-as-friend-btn" data-id="<%= user.id %>">
                <i class="fa fa-user-plus"></i>
              </button>
            <% elsif not_current_user %>
              <button class="btn btn-outline-danger search-remove-as-friend-btn" data-id="<%= user.id %>">
                <i class="fa fa-user-minus"></i>
              </button>
            <% end %>
          </div>
          <%= user.full_name %><br>
          <%= online_status(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/index.html.erb
<div class="card black-card friends-card">
  <h4 class="card-header"><%= I18n.t('friends.friends') %></h4>
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <div class="nav flex-column nav-pills" role="tablist">
          <button class="btn btn-primary mb-10px" data-toggle="modal" data-target="#add-friend-modal"><i class="fa fa-plus"></i> <%= I18n.t('friends.add_friend') %></button>
          <a class="nav-link active" data-toggle="pill" data-target="#friends" href="#0" role="tab"><%= I18n.t('friends.friends') %> <span class="badge badge-secondary"><%= @friends.count %></span></a>
          <a class="nav-link" data-toggle="pill" data-target="#pending" href="#0" role="tab"><%= I18n.t('friends.pending') %> <span class="badge badge-secondary"><%= @pending.count %></span></a>
        </div>
      </div>
      <div class="col-md-9">
        <div class="tab-content">
          <div class="tab-pane fade show active" id="friends" role="tabpanel">
            <%= render partial: 'friends/friends', locals: {friends: @friends} %>
          </div>
          <div class="tab-pane fade" id="pending" role="tabpanel">
            <%= render partial: 'friends/pending', locals: {pending: @pending} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Search Users Modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="add-friend-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= I18n.t('friends.add_friend') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="add-friend-modal-body">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="<%= I18n.t('search.user_name') %>" id="add-friend-modal-input">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="button" id="add-friend-modal-search-btn"><%= I18n.t('search.search') %></button>
          </div>
        </div>
        <div id="add-friend-modal-result">
          
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= I18n.t('modal.close') %></button>
      </div>
    </div>
  </div>
</div>