config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'connect', sign_out: 'disconnect', sign_up: 'enlist', edit: 'pilot' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  # Static Pages
  root 'static_pages#home'
  get '/credits', to: 'static_pages#credits'
  get '/nojs', to: 'static_pages#nojs'
  get '/support', to: 'static_pages#support'
  get '/donate', to: 'static_pages#donate'
  post '/support_ticket/create', to: 'static_pages#create_support_ticket', as: :create_support_ticket

  # Factions
  resources :factions, only: [:index]
  scope :factions do
    post 'choose', to: 'factions#choose_faction', as: :choose_faction
  end

  # Game
  get '/game', to: 'game#index'
  scope :game do
    post 'warp', to: 'game#warp'
    post 'jump', to: 'game#jump'
    get 'local_players', to: 'game#local_players'
    get 'ship_info', to: 'game#ship_info'
    get 'player_info', to: 'game#player_info'
    get 'chat', to: 'game#chat'
    get 'system_card', to: 'game#system_card'
    get 'locations_card', to: 'game#locations_card'
  end

  # User
  scope :user do
    get 'info/:id', to: 'users#info'
    post 'update_bio', to: 'users#update_bio'
    post 'place_bounty', to: 'users#place_bounty'
  end

  # Mails
  resources :game_mails, only: [:index, :new, :create, :show], path: 'mails'

  # Station
  scope :stations do
    post 'dock', to: 'stations#dock'
    post 'undock', to: 'stations#undock'
    post 'buy', to: 'stations#buy'
    post 'store', to: 'stations#store'
    post 'load', to: 'stations#load'
    post 'dice_roll', to: 'stations#dice_roll'
  end
  get '/station', to: 'stations#index'

  # Map
  get '/map', to: 'static_pages#map'

  # Assets
  get '/assets', to: 'game#assets'

  # Ships
  scope :ship do
    post 'activate', to: 'ships#activate'
    post 'target', to: 'ships#target'
    post 'untarget', to: 'ships#untarget'
    get 'cargohold', to: 'ships#cargohold'
    post 'eject_cargo', to: 'ships#eject_cargo'
    get 'info', to: 'ships#info'
    post 'insure', to: 'ships#insure'
    post 'custom_name', to: 'ships#custom_name'
    get 'upgrade_modal', to: 'ships#upgrade_modal'
    post 'upgrade', to: 'ships#upgrade'
  end

  # Asteroids
  scope :asteroid do
    post 'mine', to: 'asteroids#mine'
    post 'stop_mine', to: 'asteroids#stop_mine'
  end

  # NPCs
  scope :npc do
    post 'target', to: 'npcs#target'
    post 'untarget', to: 'npcs#untarget'
  end

  # Structures
  scope :structure do
    post 'open_container', to: 'structures#open_container'
    post 'pickup_cargo', to: 'structures#pickup_cargo'
    post 'attack', to: 'structures#attack'
    post 'abandoned_ship', to: 'structures#abandoned_ship'
    get 'monument_info', to: 'structures#monument_info'
  end

  # Friends
  get 'friends', to: 'friends#index'
  scope :friends do
    post 'add_friend', to: 'friends#add_friend'
    post 'accept_request', to: 'friends#accept_request'
    post 'remove_friend', to: 'friends#remove_friend'
    post 'search', to: 'friends#search'
  end

  # Chat
  scope :chat do
    post 'join', to: 'chat_rooms#join'
    post 'create', to: 'chat_rooms#create'
    post 'leave', to: 'chat_rooms#leave'
    post 'start_conversation', to: 'chat_rooms#start_conversation'
    post 'search', to: 'chat_rooms#search'
  end

  # Fleets
  scope :fleet do
    post 'invite', to: 'fleets#invite'
    post 'accept_invite', to: 'fleets#accept_invite'
    post 'remove', to: 'fleets#remove'
  end

  # Equipment
  scope :equipment do
    post 'update', to: 'equipment#update'
    post 'switch', to: 'equipment#switch'
    get 'info', to: 'equipment#info'
  end

  # Market
  scope :market do
    get 'list', to: 'market#list'
    get 'search', to: 'market#search'
    post 'buy', to: 'market#buy'
    post 'appraisal', to: 'market#appraisal'
    post 'sell', to: 'market#sell'
    get 'my_listings', to: 'market#my_listings'
    post 'delete_listing', to: 'market#delete_listing'
    post 'create_buy', to: 'market#create_buy'
    post 'fulfill_buy', to: 'market#fulfill_buy'
  end

  # Systems
  scope :system do
    get 'info', to: 'systems#info'
    post 'route', to: 'systems#route'
    post 'clear_route', to: 'systems#clear_route'
    post 'scan', to: 'systems#scan'
    post 'directional_scan', to: 'systems#directional_scan'
    post 'jump_drive', to: 'systems#jump_drive'
  end

  # Missions
  scope :mission do
    get 'info', to: 'missions#info'
    post 'accept', to: 'missions#accept'
    post 'finish', to: 'missions#finish'
    get 'popup', to: 'missions#popup'
    post 'abort', to: 'missions#abort'
  end

  # Blueprints
  scope :blueprint do
    post 'buy', to: 'blueprints#buy'
    get 'modal', to: 'blueprints#modal'
  end

  # Factory
  scope :factory do
    get 'modal', to: 'factories#modal'
    post 'craft', to: 'factories#craft'
    get 'dismantle_modal', to: 'factories#dismantle_modal'
    post 'dismantle', to: 'factories#dismantle'
  end

  # Corporation
  resources :corporations, only: [:index, :new, :create], path: 'corporation'
  scope :corporation do
    post 'update_motd', to: 'corporations#update_motd'
    post 'update_corporation', to: 'corporations#update_corporation'
    post 'kick_user', to: 'corporations#kick_user'
    get 'change_rank_modal', to: 'corporations#change_rank_modal'
    post 'change_rank', to: 'corporations#change_rank'
    post 'deposit_credits', to: 'corporations#deposit_credits'
    post 'withdraw_credits', to: 'corporations#withdraw_credits'
    get 'info', to: 'corporations#info'
    get 'apply_modal', to: 'corporations#apply_modal'
    post 'apply', to: 'corporations#apply'
    post 'accept_application', to: 'corporations#accept_application'
    post 'reject_application', to: 'corporations#reject_application'
    post 'disband', to: 'corporations#disband'
    post 'search', to: 'corporations#search'
    get 'sort_roster', to: 'corporations#sort_roster'
  end

  # Community
  scope :community do
    get '/', to: 'communities#index', as: :community
  end

  # Discourse
  get 'discourse/sso' => 'discourse_sso#sso'

  # Admin
  scope :admin do
    get '/', to: 'admin#index', as: :admin
    post 'search', to: 'admin#search'
    post 'teleport', to: 'admin#teleport'
    post 'set_credits', to: 'admin#set_credits'
    post 'ban', to: 'admin#ban'
    post 'unban', to: 'admin#unban'
    post 'server_message', to: 'admin#server_message'
    post 'mute', to: 'admin#mute'
    post 'unmute', to: 'admin#unmute'
    post 'delete_chat', to: 'admin#delete_chat'
  end

  # Polls
  scope :poll do
    post 'create', to: 'polls#create'
    post 'upvote', to: 'polls#upvote'
    post 'downvote', to: 'polls#downvote'
    post 'move_up', to: 'polls#move_up'
    post 'delete', to: 'polls#delete'
  end

  # ActionCable
  mount ActionCable.server => '/cable'

end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  skip_before_action :redirect_if_no_faction

  def index
    redirect_to game_path if current_user.faction
    @factions = Faction.all
  end

  def choose_faction
    faction = Faction.ensure(params[:id])
    raise RedirectRequest.new(game_path, error: 'Haste makes waste') if !faction || current_user.faction

    rand_location = faction.locations.station.random_row
    raise RedirectRequest.new(factions_path, error: 'errors.something_went_wrong') if !rand_location

    if !current_user.update(faction: faction, location: rand_location, docked: true)
      raise RedirectRequest.new(factions_path, error: 'errors.something_went_wrong')
    end

    # Give player ship and equipment
    current_user.give_nano

    # Add user to rookie channel
    ChatRoom.ensure('ROOKIES').users << current_user

    redirect_to game_path
  end
end

app/views/factions/index.html.erb
<div class="card black-card rules-help-card mb-3">
  <h5 class="card-header"><%= I18n.t('factions.rules_and_help') %></h5>
  <div class="card-body">
    <h5><%= I18n.t('factions.rules') %> (more can be found <%= link_to 'here', credits_path %>)</h5>
      <ul>
        <li><%= I18n.t('factions.rule_1') %></li>
        <li><%= I18n.t('factions.rule_2') %></li>
        <li><%= I18n.t('factions.rule_3') %></li>
        <li><%= I18n.t('factions.rule_4') %></li>
        <li><%= I18n.t('factions.rule_5') %></li>
      </ul>
    <h5><%= I18n.t('factions.help') %></h5>
      <ul>
        <li><%= I18n.t('factions.help_1') %></li>
        <li><%= I18n.t('factions.help_2') %></li>
      </ul>
  </div>
</div>

<div class="card black-card factions-card">
  <h5 class="card-header"><%= I18n.t('factions.choose_a_faction') %></h5>
  <div class="card-body">
    <div class="row">
      <% @factions.each_with_index do |faction, index| %>
        <div class="col-md-4 mb-3" style="position:relative">
          <div class="display mb-3 text-center">
            <%= image_tag("ships/#{faction.get_attribute(:placeholder)}") %>
          </div>

          <h5><%= faction.name %></h5>

          <p><%= faction.description %></p>

          <div class="<%= 'grounded' if index > 0 %>">
            <h5><%= I18n.t('factions.bonus') %></h5>

            <p class="color-green"><%= I18n.t("factions.#{faction.id}_bonus") %></p>

            <%= button_to choose_faction_path(id: faction.id), class: 'btn btn-primary btn-load', method: :post do %>
              <span><%= I18n.t('factions.choose') %></span>
              &nbsp;<i class="fas fa-arrow-right"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Tutorial Modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="tutorial-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= I18n.t('tutorial.before_you_continue') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= I18n.t('tutorial.before_you_continue_text') %></p>

        <div class="row">
          <div class="col-6">
            <a href="https://forums.stellar-invictus.com/t/piloting-101-a-guide-for-new-players" target="_blank" class="btn btn-outline-primary w-100"><%= I18n.t('tutorial.quickstart_guide') %></a>
          </div>
          <div class="col-6">
            <a href="https://forums.stellar-invictus.com/t/stellar-invictus-your-first-flight/499" target="_blank" class="btn btn-outline-primary w-100"><%= I18n.t('tutorial.advanced_guide') %></a>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= I18n.t('modal.close') %></button>
      </div>
    </div>
  </div>
</div>

<script>
  $('#tutorial-modal').modal('show');
  $( document ).on('turbolinks:load', function() {
    gtag('event', 'conversion', {'send_to': 'AW-878935501/xiDMCJ2mvpQBEM37jaMD'});
  });
</script>